# Generated by Django 3.2.13 on 2022-12-09 17:20

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=100, validators=[accounts.models.validate_text]),
        ),
    ]
