version: '3'
services:
    backend:
        image: unboxing96/python:3.7-alpine
        ports:
            - "8000:8000"
        depends_on:
            - redis
    redis:
        image: redis:5
        ports:
            - "6379:6379"