a = int(input())
b = int(input())
c = int(input())
d = int(input())
e = int(input())
f = int(input())
g = int(input())
h = int(input())
i = int(input())
y = [a,b,c,d,e,f,g,h,i]
print(max(y))
print(y.index(max(y))+1)